openapi: 3.0.0
paths:
  /api/v1/neighborhoods:
    get:
      operationId: NeighborhoodController_findAll
      parameters: []
      responses:
        "200":
          description: List all neighborhoods watched by this instance.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NeighborhoodDto"
    put:
      operationId: NeighborhoodController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateNeighborhoodDto"
      responses:
        "200":
          description: ""
  /api/v1/neighborhoods/{address}:
    get:
      operationId: NeighborhoodController_findOne
      parameters: []
      responses:
        "200":
          description: Show info about one neighborhood watched by this instance.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NeighborhoodDto"
    delete:
      operationId: NeighborhoodController_remove
      parameters: []
      responses:
        "200":
          description: ""
info:
  title: MANY-Explorer
  description: MANY Protocol Explorer API
  version: "0.1"
  contact: {}
tags: []
servers: []
components:
  schemas:
    NeighborhoodDto:
      type: object
      properties:
        id:
          type: number
        address:
          type: string
        url:
          type: string
        name:
          type: string
        description:
          type: string
      required:
        - id
        - address
        - url
        - name
    CreateNeighborhoodDto:
      type: object
      properties:
        url:
          type: string
        name:
          type: string
        description:
          type: string
      required:
        - url
        - name
